import React, { useState, useEffect } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { useAuth } from './contexts/AuthContext';
import { useTranslation } from 'react-i18next';
import YouProfile from './components/YouProfile';
import MessengerPanel from './components/MessengerPanel';
import OrbNavStrip from './components/OrbNavStrip';
import './styles/YouProfile.css';
import './styles/You.css';

const API_URL = import.meta.env.PROD ? '' : (import.meta.env.VITE_API_URL || 'http://localhost:5000');

type YouTab = 'profile' | 'messages';

const You: React.FC = () => {
  const { user } = useAuth();
  const { t } = useTranslation();
  const [searchParams, setSearchParams] = useSearchParams();
  const navigate = useNavigate();
  const [unreadCount, setUnreadCount] = useState(0);

  const tabParam = searchParams.get('tab') as YouTab | null;
  const activeTab: YouTab = tabParam === 'messages' ? 'messages' : 'profile';
  const startWith = searchParams.get('startWith') || undefined;

  // `/you?u=<id>` was the original (and, for a while, the only) way to view
  // someone else's profile — still generated by already-shared links out in
  // the wild (server/share/routes.ts used to build these; now-existing
  // shares keep working). /profile/:id is the canonical route now (added so
  // Sparks/Writers Hub could link to a creator's profile directly, from
  // outside You). Redirecting here instead of also rendering UserProfile
  // inline means there is exactly one profile-viewing experience — one
  // component, one close/back behavior — instead of two that quietly
  // diverged.
  const viewUserId = searchParams.get('u') || undefined;
  const viewingOther = !!viewUserId && viewUserId !== user?.id;
  useEffect(() => {
    if (viewingOther) navigate(`/profile/${viewUserId}`, { replace: true });
  }, [viewingOther, viewUserId, navigate]);

  const refreshUnread = () => {
    axios
      .get<{ items: { unreadCount: number }[] }>(`${API_URL}/api/messenger/conversations`, { withCredentials: true })
      .then(res => {
        const total = (res.data.items || []).reduce((s, c) => s + (c.unreadCount || 0), 0);
        setUnreadCount(total);
      })
      .catch(() => {});
  };

  // Fetch on mount, on every tab switch, and every 60 s while on profile tab
  useEffect(() => {
    refreshUnread();
  }, [activeTab]);

  useEffect(() => {
    const id = setInterval(refreshUnread, 60_000);
    return () => clearInterval(id);
  }, []);

  const switchTab = (tab: YouTab) => {
    if (tab === 'profile') {
      setSearchParams({});
    } else {
      setSearchParams({ tab });
    }
  };

  // When navigating to messages with startWith, we need display name too.
  // We derive initialUserName from the URL or leave it as the user ID — the panel
  // calls openOrCreateConv which uses recipientId, so the name shown updates after load.
  const initialUserName = searchParams.get('startWithName') || startWith || '';

  return (
    <div className="you-page orbit-ambient" data-module="you">
      <div className="you-tabs orbit-header">
        <button
          className={`you-tab${activeTab === 'profile' ? ' active' : ''}`}
          onClick={() => switchTab('profile')}
        >
          {t('you.profile', 'Profile')}
        </button>
        <button
          className={`you-tab${activeTab === 'messages' ? ' active' : ''}`}
          onClick={() => switchTab('messages')}
        >
          {t('you.messages', 'Messages')}
          {unreadCount > 0 && <span className="you-tab-badge">{unreadCount}</span>}
        </button>
      </div>

      <OrbNavStrip current="you" />

      <div className="you-content">
        {activeTab === 'profile' && !viewingOther && (
          <YouProfile userName={user?.name || 'User'} />
        )}
        {activeTab === 'messages' && (
          <div className="you-messenger-wrap">
            <MessengerPanel
              initialUserId={startWith}
              initialUserName={initialUserName}
              onUnreadCountChange={setUnreadCount}
            />
          </div>
        )}
      </div>
    </div>
  );
};

export default You;
