/* src/mara-core.ts */
import { startAutonomousLoop } from "./mara-brain/autonomous-loop";
import { runWebResearch } from "./mara-brain/agents/web-research";
import { runPlatformAnalyzer } from "./mara-brain/agents/platform-analyzer";
import { runGeminiLearner } from "./mara-brain/agents/gemini-learner";
import { db } from "./db";
import axios from "axios";

class MaraCore {
  isRunning: boolean = false;

  async start() {
    if (this.isRunning) return;
    this.isRunning = true;

    console.log("🚀 Mara Core V2 ONLINE");

    // Start autonomous brain loop
    if (process.env.PROCESS_AI_TASKS === "true") {
      try {
        startAutonomousLoop();
      } catch (err) {
        console.error("❌ startAutonomousLoop failed:", err);
      }
    }

    // Rulează cicluri inteligente
    setInterval(() => void this.runFullCycle(), 120000); // 2 min
    setInterval(() => void this.generateContent(), 300000); // 5 min
    setInterval(() => void this.analyzeUsers(), 180000); // 3 min
  }

  // 🧠 GÂNDIRE + ÎNVĂȚARE
  async runFullCycle(): Promise<void> {
    try {
      console.log("🧠 Mara thinking...");

      const insights: any = await runPlatformAnalyzer();

      const research: any[] = await runWebResearch(
        "AI trends, crypto trading, TikTok growth, online money"
      );

      const learning: any = await runGeminiLearner(research);

      await db.prepare(`
        INSERT INTO mara_self_reflection (content, confidence, created_at)
        VALUES (?, ?, ?)
      `).run(
        JSON.stringify({
          type: "learning_cycle",
          insights,
          research,
          learning,
          time: new Date().toISOString()
        }),
        Math.random(),
        new Date().toISOString()
      );

      console.log("✅ Learning complete");
    } catch (err) {
      console.error("❌ Thinking error:", err);
    }
  }

  // 🎥 GENERARE CONTENT (REELS / POSTĂRI)
  async generateContent(): Promise<void> {
    try {
      console.log("🎥 Generating content...");

      const topics: any[] = await runWebResearch("viral TikTok ideas AI, crypto, motivation");

      const content = {
        title: "AI Generated Post",
        idea: topics && topics.length > 0 ? (topics[0].title ?? "Make money with AI") : "Make money with AI",
        description: "Generated by Mara AI",
        createdAt: new Date().toISOString()
      };

      await db.prepare(`
        INSERT INTO mara_platform_insights (content, created_at)
        VALUES (?, ?)
      `).run(JSON.stringify(content), new Date().toISOString());

      console.log("🔥 Content created:", content.idea);
    } catch (err) {
      console.error("❌ Content error:", err);
    }
  }

  // 💰 ANALIZĂ USERI (MONETIZARE)
  async analyzeUsers(): Promise<void> {
    try {
      console.log("💰 Analyzing users...");

      const users: any[] = await db.prepare(`SELECT * FROM users`).all();

      const payingPotential = (users || []).map((u: any) => ({
        id: u.id,
        score: Math.random()
      }));

      await db.prepare(`
        INSERT INTO mara_platform_insights (content, created_at)
        VALUES (?, ?)
      `).run(JSON.stringify({
        type: "user_analysis",
        data: payingPotential,
        time: new Date().toISOString()
      }), new Date().toISOString());

      console.log("📊 User analysis done");
    } catch (err) {
      console.error("❌ User analysis error:", err);
    }
  }

  // 🌐 INTERNET DIRECT (fallback simplu)
  async quickSearch(query: string): Promise<any[]> {
    try {
      const res = await axios.get("https://api.tavily.com/search", {
        params: {
          query,
          api_key: process.env.TAVILY_API_KEY
        }
      });

      return res.data?.results ?? [];
    } catch (err) {
      console.error("❌ quickSearch error:", err);
      return [];
    }
  }
}

export const maraCore = new MaraCore();
export default MaraCore;
