#!/usr/bin/env python3
"""Add privacyPolicy translations to generate-langs.py."""
from pathlib import Path

SRC = Path(__file__).parent / "generate-langs.py"
text = SRC.read_text(encoding="utf-8")

# Privacy policy translations for the 5 comprehensive languages we have translations for
# Others will use English (already in en.json)
PP_DATA = {
    "ro": {"title":"Politica de Confidentialitate","updated":"Ultima actualizare: 1 iunie 2026","back":"Inapoi","s1Title":"1. Ce date colectam","s1Intro":"HelloMara colecteaza exclusiv datele necesare pentru functionarea platformei:","s1Auth":"Autentificare: adresa de email si parola (stocata hashuit cu bcrypt)","s1Content":"Continut creat: postari, reels, articole, comentarii","s1Missions":"Progres misiuni: XP si misiunile completate","s1Messages":"Mesaje private: sterse automat dupa 30 de zile","s1Session":"Sesiune: token temporar, expira la deconectare","s2Title":"2. Ce NU colectam","s2Li1":"Nu folosim Google Analytics, Facebook Pixel sau tracking extern","s2Li2":"Nu urmarim comportamentul tau in afara platformei","s2Li3":"Nu cream profiluri publicitare","s2Li4":"Nu vindem si nu impartasim datele tale cu terti","s2Li5":"Nu stocam adresa IP in mod permanent","s3Title":"3. Cum folosim datele","s3Intro":"Datele tale sunt folosite exclusiv pentru:","s3Li1":"Autentificarea si securitatea contului tau","s3Li2":"Afisarea continutului pe care l-ai creat","s3Li3":"Functionalitatile platformei (misiuni, reels, articole, comunitate)","s3Li4":"Trimiterea notificarilor pe care le-ai activat explicit","s4Title":"4. Retentia datelor","s4Li1":"Mesaje private: sterse automat dupa 30 de zile","s4Li2":"Continut publicat: pastrat cat timp contul este activ","s4Li3":"La stergerea contului: toate datele sunt eliminate irevocabil","s5Title":"5. Drepturile tale (GDPR)","s5Intro":"Conform GDPR, ai dreptul la:","s5Li1":"Acces: sa stii ce date detinem despre tine","s5Li2":"Rectificare: sa corectezi datele incorecte","s5Li3":"Stergere: sa iti stergi complet contul (butonul Sterge contul din Setari)","s5Li4":"Portabilitate: sa soliciti exportul datelor tale","s5Li5":"Opozitie: sa refuzi anumite tipuri de procesare","s6Title":"6. Cookie-uri","s6Text":"HelloMara foloseste exclusiv cookie-uri esentiale pentru sesiunea de autentificare. Nu folosim cookie-uri de marketing.","s7Title":"7. Securitate","s7Li1":"Parolele sunt hashuite cu bcrypt","s7Li2":"Comunicatia este criptata prin HTTPS","s7Li3":"Sesiunile sunt securizate si expira la deconectare","s8Title":"8. Contact","s8Text":"Pentru intrebari despre datele personale, ne poti contacta la:"},
    "de": {"title":"Datenschutzrichtlinie","updated":"Letzte Aktualisierung: 1. Juni 2026","back":"Zuruck","s1Title":"1. Welche Daten wir erfassen","s1Intro":"HelloMara erhebt nur die fur den Betrieb notwendigen Daten:","s1Auth":"Authentifizierung: E-Mail und Passwort (bcrypt-gehasht)","s1Content":"Erstellte Inhalte: Beitrage, Reels, Artikel, Kommentare","s1Missions":"Missionsfortschritt: XP und abgeschlossene Missionen","s1Messages":"Private Nachrichten: nach 30 Tagen automatisch geloscht","s1Session":"Sitzung: temporares Token, lauft bei Abmeldung ab","s2Title":"2. Was wir NICHT erfassen","s2Li1":"Kein Google Analytics, Facebook Pixel oder externes Tracking","s2Li2":"Kein Tracking ausserhalb der Plattform","s2Li3":"Keine Werbeprofile","s2Li4":"Keine Weitergabe von Daten an Dritte","s2Li5":"Keine dauerhafte IP-Speicherung","s3Title":"3. Wie wir Daten verwenden","s3Intro":"Deine Daten werden ausschliesslich verwendet fur:","s3Li1":"Kontoverifizierung und Sicherheit","s3Li2":"Anzeige deiner erstellten Inhalte","s3Li3":"Plattformfunktionen","s3Li4":"Aktivierte Benachrichtigungen","s4Title":"4. Datenspeicherung","s4Li1":"Private Nachrichten: nach 30 Tagen automatisch geloscht","s4Li2":"Veroffentlichte Inhalte: solange das Konto aktiv ist","s4Li3":"Bei Kontolöschung: alle Daten unwiderruflich entfernt","s5Title":"5. Deine Rechte (DSGVO)","s5Intro":"Gemas DSGVO hast du das Recht auf:","s5Li1":"Auskunft: welche Daten wir uber dich haben","s5Li2":"Berichtigung: falsche Daten korrigieren","s5Li3":"Loschung: Konto loschen (Schaltflache in Einstellungen)","s5Li4":"Datenubertragbarkeit","s5Li5":"Widerspruch","s6Title":"6. Cookies","s6Text":"HelloMara verwendet nur notwendige Cookies. Kein Marketing-Tracking.","s7Title":"7. Sicherheit","s7Li1":"Passworter mit bcrypt gehasht","s7Li2":"HTTPS-Verschlusselung","s7Li3":"Gesicherte Sitzungen","s8Title":"8. Kontakt","s8Text":"Fur Fragen zu deinen Daten:"},
    "fr": {"title":"Politique de confidentialite","updated":"Derniere mise a jour : 1er juin 2026","back":"Retour","s1Title":"1. Quelles donnees nous collectons","s1Intro":"HelloMara collecte uniquement les donnees necessaires:","s1Auth":"Authentification : email et mot de passe (bcrypt)","s1Content":"Contenu cree : publications, reels, articles, commentaires","s1Missions":"Progres des missions : XP et missions completees","s1Messages":"Messages prives : supprimes automatiquement apres 30 jours","s1Session":"Session : token temporaire, expire a la deconnexion","s2Title":"2. Ce que nous ne collectons PAS","s2Li1":"Pas de Google Analytics ni tracking externe","s2Li2":"Pas de suivi hors plateforme","s2Li3":"Pas de profils publicitaires","s2Li4":"Pas de vente ni partage de donnees","s2Li5":"Pas de stockage permanent de l'IP","s3Title":"3. Comment nous utilisons les donnees","s3Intro":"Tes donnees sont utilisees exclusivement pour :","s3Li1":"Authentification et securite du compte","s3Li2":"Affichage du contenu cree","s3Li3":"Fonctionnalites de la plateforme","s3Li4":"Envoi des notifications activees","s4Title":"4. Conservation","s4Li1":"Messages prives : supprimes apres 30 jours","s4Li2":"Contenu publie : conserve tant que le compte est actif","s4Li3":"A la suppression : toutes les donnees effacees","s5Title":"5. Tes droits (RGPD)","s5Intro":"Conformement au RGPD, tu as le droit de :","s5Li1":"Acces a tes donnees","s5Li2":"Rectification des erreurs","s5Li3":"Effacement du compte (bouton dans Parametres)","s5Li4":"Portabilite des donnees","s5Li5":"Opposition","s6Title":"6. Cookies","s6Text":"HelloMara utilise uniquement des cookies essentiels. Pas de cookies marketing.","s7Title":"7. Securite","s7Li1":"Mots de passe haches avec bcrypt","s7Li2":"HTTPS","s7Li3":"Sessions securisees","s8Title":"8. Contact","s8Text":"Pour questions sur tes donnees :"},
    "es": {"title":"Politica de privacidad","updated":"Ultima actualizacion: 1 de junio de 2026","back":"Volver","s1Title":"1. Que datos recopilamos","s1Intro":"HelloMara recopila solo los datos necesarios:","s1Auth":"Autenticacion: correo y contrasena (bcrypt)","s1Content":"Contenido creado: publicaciones, reels, articulos, comentarios","s1Missions":"Progreso en misiones: XP y misiones completadas","s1Messages":"Mensajes privados: eliminados automaticamente despues de 30 dias","s1Session":"Sesion: token temporal, expira al cerrar sesion","s2Title":"2. Lo que NO recopilamos","s2Li1":"No usamos rastreo externo","s2Li2":"No rastreamos fuera de la plataforma","s2Li3":"No creamos perfiles publicitarios","s2Li4":"No vendemos ni compartimos datos","s2Li5":"No almacenamos IP permanentemente","s3Title":"3. Como usamos los datos","s3Intro":"Tus datos se usan exclusivamente para:","s3Li1":"Autenticacion y seguridad","s3Li2":"Mostrar contenido creado","s3Li3":"Funcionalidades de la plataforma","s3Li4":"Notificaciones activadas","s4Title":"4. Retencion de datos","s4Li1":"Mensajes: eliminados despues de 30 dias","s4Li2":"Contenido: retenido mientras la cuenta este activa","s4Li3":"Al eliminar cuenta: todos los datos eliminados","s5Title":"5. Tus derechos (RGPD)","s5Intro":"Segun el RGPD, tienes derecho a:","s5Li1":"Acceso","s5Li2":"Rectificacion","s5Li3":"Supresion (boton en Ajustes)","s5Li4":"Portabilidad","s5Li5":"Oposicion","s6Title":"6. Cookies","s6Text":"Solo cookies esenciales. Sin cookies de marketing.","s7Title":"7. Seguridad","s7Li1":"Contrasenas cifradas con bcrypt","s7Li2":"HTTPS","s7Li3":"Sesiones protegidas","s8Title":"8. Contacto","s8Text":"Para preguntas sobre tus datos:"},
    "ru": {"title":"Politika konfidencialnosti","updated":"Posledneye obnovleniye: 1 iyunya 2026","back":"Nazad","s1Title":"1. Kakiye dannyye my sobiraYem","s1Intro":"HelloMara sobirayet tolko dannyye, neobkhodimyye dlya raboty platformy:","s1Auth":"Autentifikaciya: email i parol (bcrypt)","s1Content":"Sozданnyy kontent: posty, reels, stati, kommentarii","s1Missions":"Progress missiy: XP i zavershyonnyye missii","s1Messages":"Lichnyye soobshcheniya: udalyayutsya cherez 30 dney","s1Session":"Sessiya: vremennyy token","s2Title":"2. Chto my NE sobiraYem","s2Li1":"Nikakoy analitiki tretikh storon","s2Li2":"Ni otslezhivaniya za predelami platformy","s2Li3":"Nikakikh reklamnykh profiley","s2Li4":"Nikakoy peredachi dannykh tretim licam","s2Li5":"IP ne khranitsya postoyanno","s3Title":"3. Kak my ispol'zuYem dannyye","s3Intro":"Dannyye ispol'zuyutsya isklyuchitel'no dlya:","s3Li1":"Autentifikacii i bezopasnosti akkaunta","s3Li2":"Otobrazheniya sozdannogo kontenta","s3Li3":"Funkcy platformy","s3Li4":"Uvedomleniy, kotoryye vy aktivirovali","s4Title":"4. Khraneniye dannykh","s4Li1":"Soobshcheniya: udalyayutsya cherez 30 dney","s4Li2":"Kontenty: khranitsya poka akkauunt aktiven","s4Li3":"Pri udalenii akkaunta: vse dannyye udalyayutsya","s5Title":"5. Vashi prava (GDPR)","s5Intro":"Soglasno GDPR, u vas est pravo na:","s5Li1":"Dostup k vashim dannym","s5Li2":"Ispravleniye oshibok","s5Li3":"Udaleniye akkaunta (knopka v Nastroykakh)","s5Li4":"Portiruyemost dannykh","s5Li5":"Vozrazheniye","s6Title":"6. Kuki","s6Text":"Tolko neobkhodimyye kuki. Nikakogo marketinga.","s7Title":"7. Bezopasnost","s7Li1":"Paroli kheshiruyutsya s bcrypt","s7Li2":"HTTPS","s7Li3":"Seysy zashchishcheny","s8Title":"8. Kontakty","s8Text":"Po voprosam o vashikh dannykh:"},
}

MARKER = "# ---------------------------------------------------------------------------\n# Auth error-code translations."

insertion = "\n# ── Privacy Policy translations ──────────────────────────────────────────\n"
insertion += "_PP_TRANSLATIONS = " + repr(PP_DATA) + "\n"
insertion += "\nfor _lang, _ppdata in _PP_TRANSLATIONS.items():\n"
insertion += "    if _lang in OVERRIDES:\n"
insertion += "        OVERRIDES[_lang]['privacyPolicy'] = _ppdata\n\n"

assert MARKER in text, "Marker not found!"
text = text.replace(MARKER, insertion + MARKER, 1)
SRC.write_text(text, encoding="utf-8")
print("Privacy Policy patch inserted")
